/** Auto-generated by scripts/generate-about-expanded.mjs — do not edit by hand. */
export type AboutContentBlock =
  | { type: "p"; html: string }
  | { type: "h2"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "pre"; code: string };

export const expandedAboutContent: Record<string, AboutContentBlock[]> = {
  "dht22-sensor-overview": [
      { type: "p", html: "The DHT22 (also sold as AM2302) is the digital sensor at the heart of this garage build. It reports relative humidity and air temperature over a single data line, which keeps wiring simple when you need multiple zones. Understanding its behavior helps you interpret noisy readings and set realistic expectations compared with lab-grade equipment." },
      { type: "h2", text: "What the DHT22 measures" },
      { type: "p", html: "Each read returns humidity (0–100 %RH) and temperature (typically −40 to 80 °C spec range). The firmware converts values to Fahrenheit for JSON consumers while the LCD may show either scale. Readings represent the air pocket around the sensor body—not surface temperature of a pipe or concrete slab unless you mount the probe against that surface intentionally." },
      { type: "p", html: "Datasheet accuracy is roughly ±0.5 °C and ±2–5 %RH under stable conditions. In drafty garages, rapid door openings can produce short spikes that are real air movement, not sensor failure. Compare with <a class=\"text-link\" href=\"/about/probe-mounting-enclosures\">probe placement guidance</a> before replacing hardware." },
      { type: "h2", text: "Timing and bus behavior" },
      { type: "p", html: "DHT22 sensors enforce a minimum interval between reads—often two seconds. The sketch polls on a timer and skips overlapping requests. Violating the interval returns stale or error values, which is why firmware includes retry logic described in <a class=\"text-link\" href=\"/about/dht22-read-errors-retries\">DHT22 read errors and retries</a>." },
      { type: "ul", items: ["**Power:** 3.3–5 V DC; share ground with the Arduino.","**Data:** One GPIO per sensor with a pull-up resistor on the line.","**Cable length:** Keep runs modest; long unshielded wires pick up noise.","**Enclosure:** Ventilated housing avoids sun-heated stale air—see the mounting guide."] },
      { type: "h2", text: "Where it fits in the stack" },
      { type: "p", html: "Probes feed the <a class=\"text-link\" href=\"/about/arduino-sketches\">Arduino sketch</a>, which publishes JSON consumed by the website. Follow the <a class=\"text-link\" href=\"/about/data-flow\">end-to-end data flow</a> when debugging mismatches between LCD and web values. Pin-level wiring is documented in <a class=\"text-link\" href=\"/about/dht22-data-line-wiring\">DHT22 data line wiring</a>." }
  ],

  "probe-mounting-enclosures": [
      { type: "p", html: "A perfect sensor in the wrong location lies. Garage probes should sample the air volume where stored goods and people actually experience conditions—not the hottest sun patch on the floor or the coldest air seeping under a door." },
      { type: "h2", text: "Height and location" },
      { type: "p", html: "Mount at roughly four to five feet on an interior wall, away from the garage door plane and direct sunlight through windows. North and west walls often track outdoor swings more slowly, which can be useful for freeze-risk monitoring. See <a class=\"text-link\" href=\"/about/multi-zone-garage-layout\">multi-zone layout</a> when placing more than one probe." },
      { type: "h2", text: "Enclosures and airflow" },
      { type: "ul", items: ["Use **ventilated project boxes** so the sensor breathes ambient air.","Avoid sealing probes inside waterproof cases without vents—humidity lags reality.","Route cables down from the box so condensation does not drip into electronics.","Label each cable at both ends before climbing a ladder twice."] },
      { type: "h2", text: "Common mistakes" },
      { type: "p", html: "Probes zip-tied to metal door tracks, sitting on freezers, or dangling in front of exhaust fans produce dramatic but misleading graphs. The <a class=\"text-link\" href=\"/about/probe-demo\">interactive probe demo</a> shows how door and sun inputs move zones differently—use it when validating placement. For seasonal context, read <a class=\"text-link\" href=\"/about/seasonal-garage-patterns\">seasonal garage patterns</a>." }
  ],

  "multi-zone-garage-layout": [
      { type: "p", html: "Large garages behave like several microclimates. A single average hides the coldest corner where pipes run and the warmest bay under a sunny roof. Multiple probes turn one vague number into actionable zone data." },
      { type: "h2", text: "Example zone map" },
      { type: "ol", items: ["**Zone 0 — Door-adjacent:** Captures infiltration when the door opens; expect wide swings.","**Zone 1 — Interior workbench:** Represents where you stand and where tools live.","**Optional third — Ceiling or attic knee wall:** Spots hot air stratification in summer."] },
      { type: "h2", text: "Firmware and dashboard alignment" },
      { type: "p", html: "JSON keys <code>0</code>, <code>1</code>, and <code>avg</code> map to dashboard labels you configure after sign-in—see <a class=\"text-link\" href=\"/about/probe-mapping-labels\">probe mapping and labels</a>. The average is a convenience snapshot for history, not a substitute for checking each zone during cold snaps." },
      { type: "p", html: "Dual-probe wiring and LCD layout are covered in <a class=\"text-link\" href=\"/about/arduino-dht22-lcd\">DHT22 sensors and LCD display</a> and <a class=\"text-link\" href=\"/about/dual-probe-averaging\">dual-probe averaging logic</a>." },
      { type: "h2", text: "When to add another probe" },
      { type: "ul", items: ["**Split-level garage:** Floor and loft can differ by 10 °F on calm winter nights.","**Shared wall with house:** Interior partition may stay warmer than the exterior bay.","**Workshop corner with heat gun use:** Isolate occasional spikes from whole-garage trends."] }
  ],

  "probe-mapping-labels": [
      { type: "p", html: "Raw JSON exposes probes as numeric keys. The dashboard translates those keys into labels such as “North wall” or “Door bay” so visitors understand what they are reading without memorizing firmware indices." },
      { type: "h2", text: "Configuring mappings" },
      { type: "p", html: "Signed-in users add HTTPS feed URLs under dashboard temperature feed settings—detailed in <a class=\"text-link\" href=\"/about/configuring-temperature-feeds\">configuring temperature feeds</a>. Each enabled probe key gets a display name. Typos in keys silently hide readings even when the feed is healthy, so verify against curl output or <a class=\"text-link\" href=\"/about/json-probe-output-schema\">JSON probe output schema</a>." },
      { type: "h2", text: "Naming conventions" },
      { type: "ul", items: ["Include **location and height** if zones are similar (“East wall, high”).","Keep names short for mobile stat cards.","Document GPIO-to-key mapping on the bench for future you.","Use the average key only for summary history, not as a zone label."] },
      { type: "h2", text: "Related guides" },
      { type: "p", html: "Start with <a class=\"text-link\" href=\"/about/temperature-probes\">temperature probes and their uses</a>, then follow <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">home page probe fetch</a> for how mappings reach the public home page." }
  ],

  "garage-door-temperature-swings": [
      { type: "p", html: "The garage door is the dominant hole in the thermal envelope. Opening it exchanges a large slab of indoor air with outdoor conditions in seconds—often faster than the rest of the structure responds. Probes near the door record this clearly; probes farther away may barely notice a single short opening." },
      { type: "h2", text: "What probes show" },
      { type: "p", html: "Expect sudden drops in winter or jumps in summer humidity when cold or humid outdoor air rolls in. Short spikes during brief errands are normal. Prolonged door-open work sessions can drive the entire bay toward outdoor dew point—watch for condensation on metal tools afterward." },
      { type: "h2", text: "Separating signal from placement error" },
      { type: "p", html: "If every daily spike aligns with commute times, your door-adjacent probe is doing its job. If the interior probe mirrors the same amplitude, consider relocating it—see <a class=\"text-link\" href=\"/about/probe-mounting-enclosures\">probe mounting</a>. Compare patterns with <a class=\"text-link\" href=\"/about/temperature-changes\">temperature changes overview</a> and the <a class=\"text-link\" href=\"/about/probe-demo\">probe demo</a> door toggle." },
      { type: "h2", text: "Mitigation without new hardware" },
      { type: "ul", items: ["**Weather stripping** on the door reduces idle infiltration between openings.","**Interior probe** on the opposite wall gives context for how far the wave travels.","**History charts** help distinguish one-off events from chronic heat loss—see <a class=\"text-link\" href=\"/about/history-dashboard-browsing\">history dashboard browsing</a>."] }
  ],

  "sun-load-garage-walls": [
      { type: "p", html: "Sun load heats opaque walls even when outdoor air temperature is moderate. Dark siding, uninsulated sheathing, and metal doors store heat that bleeds inward for hours after peak outdoor temps. Probes on sun-facing walls often peak later than the weather app suggests." },
      { type: "h2", text: "Seasonal patterns" },
      { type: "ul", items: ["**Summer:** Interior garage temps can exceed outdoor highs in late afternoon.","**Winter:** Low sun angle may still warm south walls on clear days.","**Shoulder seasons:** Large diurnal swing with delayed interior maximum."] },
      { type: "h2", text: "Monitoring implications" },
      { type: "p", html: "Pair wall-adjacent probes with a more sheltered interior zone to separate sun-driven drift from whole-garage trends. <a class=\"text-link\" href=\"/about/seasonal-garage-patterns\">Seasonal patterns</a> explains how to read multi-month history without overreacting to a single hot afternoon." },
      { type: "h2", text: "Probe placement tips" },
      { type: "p", html: "Avoid mounting directly on sun-baked drywall facing south or west. A few inches of standoff inside a ventilated box still tracks wall influence without baking the sensor. <a class=\"text-link\" href=\"/about/multi-zone-garage-layout\">Multi-zone layout</a> helps assign one probe to the sunny wall and another to a shaded reference." }
  ],

  "infiltration-wind-drafts": [
      { type: "p", html: "Air leaks and wind-driven pressure differences move garage air even when the big door stays shut. Gaps around the door, soffit vents, and poorly sealed service entries let outdoor air slip in along the floor and behind stored shelving." },
      { type: "h2", text: "Wind versus door events" },
      { type: "p", html: "Door openings produce sharp, short spikes tied to human activity. Steady wind on a cold night creates a slower drift—especially on probes near the door bottom or exterior wall. Compare with <a class=\"text-link\" href=\"/about/garage-door-temperature-swings\">garage door swings</a> to tell which driver dominates." },
      { type: "h2", text: "What to watch in data" },
      { type: "ul", items: ["**Overnight plateaus** colder than forecast often mean chronic infiltration.","**Humidity rises** when warm moist outdoor air replaces dry winter indoor air.","**Zone mismatch** between door and interior probes flags draft paths."] },
      { type: "h2", text: "Next steps" },
      { type: "p", html: "Use <a class=\"text-link\" href=\"/about/historical-data\">historical data</a> to correlate windy weeks with minimum temps. Freeze planning belongs in <a class=\"text-link\" href=\"/about/freeze-protection-thresholds\">freeze protection thresholds</a> once you know your typical leak-driven floor." }
  ],

  "seasonal-garage-patterns": [
      { type: "p", html: "Garages follow the seasons with lag and damping. Unconditioned bays track outdoor extremes more closely in winter and lag behind peak summer heat when insulation and thermal mass buffer swings. Long history makes those rhythms obvious." },
      { type: "h2", text: "Winter freeze risk" },
      { type: "p", html: "Pipes and chemicals care about sustained lows, not a single cold hour. Review weekly minimums in the dashboard history rather than glancing at noon readings. Pair with <a class=\"text-link\" href=\"/about/freeze-protection-thresholds\">freeze protection thresholds</a> for actionable cutoffs." },
      { type: "h2", text: "Summer heat storage" },
      { type: "ul", items: ["**Afternoon peaks** often arrive after outdoor highs when <a class=\"text-link\" href=\"/about/sun-load-garage-walls\">sun load</a> dominates.","**Overnight cooling** may stall if the bay never fully purges hot air.","**Humidity** can climb when warm air holds more moisture near stored goods."] },
      { type: "h2", text: "Using history well" },
      { type: "p", html: "Export CSV for year-over-year comparison—see <a class=\"text-link\" href=\"/about/csv-export-spreadsheet-analysis\">CSV export and spreadsheet analysis</a>. Seasonal planning beats reacting to every daily wiggle on the home page." }
  ],

  "history-dashboard-browsing": [
      { type: "p", html: "Live readings answer “what is it now?” History answers “how bad was last week?” The signed-in dashboard charts stored Supabase rows so you can zoom from recent hours to multi-month trends without re-querying the probe on every page load." },
      { type: "h2", text: "What gets stored" },
      { type: "p", html: "Each snapshot captures probe keys, temperature, humidity, and timestamps when the site polls your configured feeds. Inserts are described in <a class=\"text-link\" href=\"/about/supabase-history-inserts\">Supabase history inserts</a>. Not every page view hits your garage—polling runs on a schedule server-side." },
      { type: "h2", text: "Reading the charts" },
      { type: "ul", items: ["**Compare zones** to see whether one corner always runs coldest.","**Look at nights** for freeze risk rather than daytime peaks.","**Spot gaps** that may indicate feed outages—see <a class=\"text-link\" href=\"/about/debugging-stale-readings\">debugging stale readings</a>."] },
      { type: "h2", text: "Export for deeper analysis" },
      { type: "p", html: "Subscribers unlock CSV export for spreadsheet pivot tables and custom graphs. Details: <a class=\"text-link\" href=\"/about/stripe-csv-subscription\">Stripe CSV subscription</a> and <a class=\"text-link\" href=\"/about/csv-export-spreadsheet-analysis\">CSV export analysis</a>." }
  ],

  "csv-export-spreadsheet-analysis": [
      { type: "p", html: "Charts in the browser are convenient; CSV export is for questions the built-in UI does not answer. Spreadsheet tools let you compute degree-hours, correlate with weather files, and share trimmed datasets with contractors or insurers." },
      { type: "h2", text: "Typical export columns" },
      { type: "p", html: "Exports include timestamps, probe identifiers, Fahrenheit and Celsius values, and humidity where available. Join on time buckets when merging with external weather CSVs. Subscription access is managed through <a class=\"text-link\" href=\"/about/stripe-csv-subscription\">Stripe billing</a>." },
      { type: "h2", text: "Analysis ideas" },
      { type: "ol", items: ["**Weekly minimum temperature** by zone for freeze planning.","**Door-event detection** by pairing sharp drops with your own activity log.","**Before/after insulation** comparison using the same date range year over year."] },
      { type: "h2", text: "Workflow tips" },
      { type: "ul", items: ["Import into **LibreOffice Calc** or Excel; freeze panes on the timestamp column.","Use pivot tables to aggregate by **hour of day** and find chronic cold windows.","Keep raw exports archived—re-derive charts when questions change."] }
  ],

  "freeze-protection-thresholds": [
      { type: "p", html: "Freeze damage happens when air or pipe-adjacent zones stay below 32 °F long enough for water to expand. Garage probes measure air, which is usually a few degrees warmer than fluid in an exterior wall cavity—so build margin into any alert threshold." },
      { type: "h2", text: "Choosing thresholds" },
      { type: "p", html: "Many owners watch for sustained air temps below 35–38 °F rather than reacting to a single 31 °F blip during a door opening. Review <a class=\"text-link\" href=\"/about/history-dashboard-browsing\">history browsing</a> for overnight plateaus, not spikes." },
      { type: "h2", text: "Zone-specific rules" },
      { type: "ul", items: ["**Door-adjacent probe:** Expect brief dips; do not treat every spike as emergency.","**Interior / pipe-wall probe:** Tighter threshold; this zone best represents risk.","**Average key:** Useful summary but can hide a cold corner—check individual zones."] },
      { type: "h2", text: "Related monitoring" },
      { type: "p", html: "Understand drivers with <a class=\"text-link\" href=\"/about/seasonal-garage-patterns\">seasonal patterns</a> and <a class=\"text-link\" href=\"/about/infiltration-wind-drafts\">infiltration</a>. Hardware reliability matters too—<a class=\"text-link\" href=\"/about/dht22-read-errors-retries\">DHT22 retries</a> prevent false alarms from bad reads." }
  ],

  "arduino-ide-setup": [
      { type: "p", html: "Firmware development starts on the bench with USB power and serial logging. The Arduino IDE (or PlatformIO) compiles C++ sketches, flashes the Uno, and opens a serial monitor for the first sanity checks before the board moves to the garage." },
      { type: "h2", text: "Board and libraries" },
      { type: "ul", items: ["**Board:** Arduino Uno (or compatible) with sufficient flash for Ethernet + LCD stacks.","**Libraries:** DHT sensor library, LiquidCrystal, Ethernet/W5100 stack as used in the repo sketch.","**Port:** Select the correct USB serial port after plugging in the programming cable."] },
      { type: "h2", text: "First flash checklist" },
      { type: "ol", items: ["Verify compile with **no errors** before disconnecting bench wiring.","Open serial monitor at **9600 baud** (or sketch default) and confirm boot messages.","Confirm LCD shows live values—see <a class=\"text-link\" href=\"/about/lcd-local-display-format\">LCD display format</a>.","curl the JSON endpoint before mounting—schema in <a class=\"text-link\" href=\"/about/json-probe-output-schema\">JSON probe output schema</a>."] },
      { type: "h2", text: "Source and wiring context" },
      { type: "p", html: "Reference firmware lives in the project GitHub repo linked from <a class=\"text-link\" href=\"/about/arduino-sketches\">Arduino sketches overview</a>. Wire the breadboard first using <a class=\"text-link\" href=\"/about/arduino-circuit-wiring\">circuit wiring</a> and <a class=\"text-link\" href=\"/about/arduino-pin-wiring\">pin wiring</a> guides." }
  ],

  "sketch-polling-main-loop": [
      { type: "p", html: "The main loop balances sensor polling, LCD refresh, and HTTP service without blocking any one task for too long. DHT22 reads take hundreds of milliseconds; Ethernet handling must remain responsive enough that dashboard fetches do not time out." },
      { type: "h2", text: "Typical loop structure" },
      { type: "ol", items: ["**Check timer:** If the poll interval elapsed, read each DHT22 with retries.","**Update LCD:** Refresh lines for probe 0, probe 1, and optional average.","**Serve HTTP:** Parse incoming client requests and return cached JSON.","**Watchdog / reconnect:** Reset or re-init Ethernet if the link dropped."] },
      { type: "h2", text: "Timing constraints" },
      { type: "p", html: "Respect the two-second minimum between DHT22 reads per sensor. Stagger probes if needed. Averaging logic is documented in <a class=\"text-link\" href=\"/about/dual-probe-averaging\">dual-probe averaging</a>. When reads fail, skip updating that key rather than publishing NaN." },
      { type: "h2", text: "Debugging on serial" },
      { type: "p", html: "Log read failures and Ethernet state during development. After deployment, rely on <a class=\"text-link\" href=\"/about/debugging-stale-readings\">stale reading diagnostics</a> on the website side. Recovery paths: <a class=\"text-link\" href=\"/about/firmware-watchdog-recovery\">firmware watchdog recovery</a>." }
  ],

  "json-probe-output-schema": [
      { type: "p", html: "Downstream systems—Python relays, Astro fetch routes, and dashboard mappings—all assume a stable JSON shape. Changing keys without updating consumers breaks probe labels and history inserts silently." },
      { type: "h2", text: "Canonical document" },
      { type: "pre", code: "{\n  \"temp\": {\n    \"0\": { \"f\": 38.2, \"c\": 3.4, \"h\": 41.0 },\n    \"1\": { \"f\": 36.8, \"c\": 2.7, \"h\": 43.5 },\n    \"avg\": { \"f\": 37.5, \"c\": 3.1, \"h\": 42.2 }\n  }\n}" },
      { type: "h2", text: "Field meanings" },
      { type: "ul", items: ["**Numeric keys** match firmware probe indices and dashboard mapping entries.","**f / c:** Fahrenheit and Celsius for the same sample.","**h:** Relative humidity percent for that probe.","**avg:** Mean across healthy probes only; omit or freeze if one sensor is offline."] },
      { type: "h2", text: "Consumers" },
      { type: "p", html: "The <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">home page fetch</a> reads this structure for public cards. <a class=\"text-link\" href=\"/about/python-feeds\">Python feeds</a> may cache the same payload. Map labels via <a class=\"text-link\" href=\"/about/probe-mapping-labels\">probe mapping</a>." }
  ],

  "firmware-watchdog-recovery": [
      { type: "p", html: "Garage hardware runs unattended for months. Rare hangs—Ethernet driver stalls, memory fragmentation, or sensor bus lockups—are cheaper to recover with a watchdog reset than with a ladder trip. A timed reset reboots the MCU and reinitializes shields and sensors." },
      { type: "h2", text: "When watchdog helps" },
      { type: "ul", items: ["**Network stack freeze** after router power blips.","**Infinite retry loop** on a disconnected DHT22 data line.","**HTTP client backlog** on the W5100 after sustained polling from the cloud."] },
      { type: "h2", text: "Implementation notes" },
      { type: "p", html: "Pet the watchdog only when the main loop completes a full cycle—sensor read, LCD update, and HTTP housekeeping. Too-aggressive petting masks real deadlocks. Pair with DHCP renew and JSON serving logic in <a class=\"text-link\" href=\"/about/sketch-polling-main-loop\">sketch polling main loop</a>." },
      { type: "h2", text: "Operational expectations" },
      { type: "p", html: "Expect a brief JSON outage during reboot—seconds, not minutes. <a class=\"text-link\" href=\"/about/debugging-stale-readings\">Stale reading debug</a> distinguishes reboot gaps from feed misconfiguration. Ethernet stacking notes: <a class=\"text-link\" href=\"/about/ethernet-shield-stacking\">Ethernet shield stacking</a>." }
  ],

  "breadboard-power-rails": [
      { type: "p", html: "The solderless breadboard distributes 5 V and ground from the Arduino to the LCD, DHT22 pull-ups, contrast pot, and Ethernet shield support components. Clean power rails reduce mysterious LCD garbage and sensor timeouts." },
      { type: "h2", text: "Rail layout" },
      { type: "ul", items: ["**Red rail:** 5 V from Arduino 5V pin (USB or barrel power when installed).","**Blue rail:** Common ground tied to Arduino GND.","**Jumpers:** Short, same-length wires where possible; one ground star point at the board."] },
      { type: "h2", text: "LCD and sensor power" },
      { type: "p", html: "The 16×2 LCD draws modest current; DHT22 peaks during conversion. If cables run long to remote probes, consider a dedicated 5 V supply with common ground rather than starving the Uno regulator. Contrast pot wiring shares ground—see <a class=\"text-link\" href=\"/about/liquid-crystal-gpio-map\">LCD GPIO map</a>." },
      { type: "h2", text: "Bench verification" },
      { type: "p", html: "Measure rail voltage under load before sealing an enclosure. Troubleshooting steps live in <a class=\"text-link\" href=\"/about/circuit-wiring-troubleshooting\">circuit wiring troubleshooting</a>. Full overview: <a class=\"text-link\" href=\"/about/arduino-circuit-wiring\">Arduino circuit wiring</a>." }
  ],

  "ethernet-shield-stacking": [
      { type: "p", html: "The W5100-based Ethernet shield stacks on the Uno and consumes SPI pins plus a chip select line. Mechanical stacking is simple; electrically you must reserve those pins and route DHT22 and LCD wires around the tall assembly." },
      { type: "h2", text: "Stack order and headers" },
      { type: "ol", items: ["Seat the **Ethernet shield** fully on Uno headers—no bent pins behind the RJ45 jack.","Route jumper wires from the top of the stack or use a **protoboard wing** for LCD pins.","Keep Ethernet cable strain relief so RJ45 flex does not lift the shield off headers."] },
      { type: "h2", text: "SPI sharing" },
      { type: "p", html: "Only one SPI device should drive the bus at a time; the W5100 owns SPI during network I/O. GPIO for DHT22 and parallel LCD are separate—details in <a class=\"text-link\" href=\"/about/spi-pins-ethernet-reserved\">SPI pins and reserved lines</a>." },
      { type: "h2", text: "Network path" },
      { type: "p", html: "DHCP on a garage router assigns the board an IP; JSON is served over HTTP on the LAN. For HTTPS at the edge, terminate TLS on <a class=\"text-link\" href=\"/about/fastapi-relay-setup\">FastAPI relay</a> instead of the MCU." }
  ],

  "circuit-wiring-troubleshooting": [
      { type: "p", html: "Intermittent readings usually trace to power, ground, or loose jumpers—not bad luck. Work methodically from rails to sensors before swapping the Arduino." },
      { type: "h2", text: "Symptom → likely cause" },
      { type: "ul", items: ["**Blank LCD:** Contrast pot, missing Vo, or wrong RS/E/D pins.","**DHT22 timeout:** Missing pull-up, swapped data/ground, or read interval too fast.","**Ethernet dead:** Shield not seated, bad cable, or SPI pin conflict with LCD wiring.","**Garbled LCD:** Floating data line or 3.3 V LCD on 5 V logic without level consideration."] },
      { type: "h2", text: "Tools" },
      { type: "p", html: "Serial logging from <a class=\"text-link\" href=\"/about/arduino-ide-setup\">Arduino IDE setup</a> confirms firmware is alive. Multimeter checks on <a class=\"text-link\" href=\"/about/breadboard-power-rails\">power rails</a> confirm 5 V under load. Pin-by-pin review: <a class=\"text-link\" href=\"/about/arduino-pin-wiring\">pin wiring</a>." },
      { type: "h2", text: "Sensor-specific help" },
      { type: "p", html: "Persistent DHT22 failures after wiring checks: <a class=\"text-link\" href=\"/about/dht22-read-errors-retries\">DHT22 read errors and retries</a> and <a class=\"text-link\" href=\"/about/dht22-data-line-wiring\">data line wiring</a>." }
  ],

  "liquid-crystal-gpio-map": [
      { type: "p", html: "The 16×2 LCD uses parallel mode in 4-bit wiring: RS, E, and four data lines map to specific Uno GPIOs matching the LiquidCrystal constructor in firmware. Backlight may be on a transistor switch for dimming or power saving." },
      { type: "h2", text: "Typical assignments" },
      { type: "p", html: "Exact pins follow the repo sketch—document your build on paper. RS and E control command versus data mode; D4–D7 carry nibbles. Contrast on Vo uses a 10k pot between 5 V and ground." },
      { type: "ul", items: ["**RS:** Register select—commands vs character data.","**E:** Enable strobe for each nibble transfer.","**D4–D7:** Upper four bits of the 8-bit interface in 4-bit mode.","**Backlight:** Often transistor-switched LED+ pin, not a GPIO data line."] },
      { type: "h2", text: "Avoiding conflicts" },
      { type: "p", html: "Do not assign LCD lines to <a class=\"text-link\" href=\"/about/spi-pins-ethernet-reserved\">SPI reserved pins</a> used by the Ethernet shield. DHT22 data pins must also stay clear—see <a class=\"text-link\" href=\"/about/dht22-data-line-wiring\">DHT22 data wiring</a>." },
      { type: "h2", text: "Display content" },
      { type: "p", html: "What appears on each row is firmware-defined in <a class=\"text-link\" href=\"/about/lcd-local-display-format\">LCD local display format</a>." }
  ],

  "dht22-data-line-wiring": [
      { type: "p", html: "Each DHT22 uses one digital GPIO for its single-wire protocol. Power and ground come from the breadboard rails; a 4.7k–10k pull-up from data to 5 V keeps the line idle high between reads." },
      { type: "h2", text: "Per-sensor connections" },
      { type: "ol", items: ["**VCC** to 5 V rail (some modules include onboard regulator for 3.3 V parts—check yours).","**DATA** to a unique GPIO with pull-up resistor.","**GND** to common ground at the Arduino."] },
      { type: "h2", text: "Cable runs to remote probes" },
      { type: "p", html: "Short twisted or paired wire reduces noise. Avoid running data parallel to AC power. If reads degrade at distance, retry logic in <a class=\"text-link\" href=\"/about/dht22-read-errors-retries\">DHT22 read errors</a> helps but physics still wins—relocate or shorten runs." },
      { type: "h2", text: "Firmware mapping" },
      { type: "p", html: "GPIO order defines JSON keys <code>0</code> and <code>1</code>. Document the mapping for <a class=\"text-link\" href=\"/about/probe-mapping-labels\">dashboard labels</a>. Sensor basics: <a class=\"text-link\" href=\"/about/dht22-sensor-overview\">DHT22 overview</a>." }
  ],

  "spi-pins-ethernet-reserved": [
      { type: "p", html: "The W5100 Ethernet shield uses hardware SPI on the Uno: MOSI, MISO, SCK, plus chip select on pin 10. Pins 10–13 and SPI lines must not be repurposed for LCD or sensors in standard layouts." },
      { type: "h2", text: "Reserved lines" },
      { type: "ul", items: ["**D10:** W5100 chip select (SS).","**D11–D13:** SPI MOSI, MISO, SCK on Uno.","**Interrupt pin:** Shield-specific; follow vendor silkscreen."] },
      { type: "h2", text: "Planning GPIO budget" },
      { type: "p", html: "LCD 4-bit mode consumes six GPIOs; two DHT22 lines consume two more—plan before adding features. Stacking details: <a class=\"text-link\" href=\"/about/ethernet-shield-stacking\">Ethernet shield stacking</a>." },
      { type: "h2", text: "Alternative stacks" },
      { type: "p", html: "If pins run out, consider I²C LCD modules or offloading HTTPS to <a class=\"text-link\" href=\"/about/python-feeds\">Python feeds</a> while keeping JSON on HTTP locally." }
  ],

  "dht22-read-errors-retries": [
      { type: "p", html: "DHT22 reads fail occasionally—timing violations, electrical noise, or a momentary bus contention. Firmware should retry a few times with backoff before marking a probe unhealthy rather than publishing garbage values to JSON." },
      { type: "h2", text: "Retry strategy" },
      { type: "ol", items: ["On **checksum or timeout error**, wait at least two seconds and retry.","Cap retries at **three to five** attempts per poll cycle.","If all fail, **omit or hold last good value**—document your choice in schema notes."] },
      { type: "h2", text: "Hardware fixes first" },
      { type: "p", html: "Verify pull-ups and grounding in <a class=\"text-link\" href=\"/about/dht22-data-line-wiring\">data line wiring</a>. Long cables and motor noise from garage door openers aggravate errors. <a class=\"text-link\" href=\"/about/circuit-wiring-troubleshooting\">Circuit troubleshooting</a> covers bench checks." },
      { type: "h2", text: "Downstream impact" },
      { type: "p", html: "Bad reads affect <a class=\"text-link\" href=\"/about/dual-probe-averaging\">averaging</a> and dashboard history. <a class=\"text-link\" href=\"/about/debugging-stale-readings\">Debugging stale readings</a> on the site helps tell sensor faults from network issues." }
  ],

  "lcd-local-display-format": [
      { type: "p", html: "The 16×2 LCD gives installers immediate feedback without Wi-Fi or a laptop. Two rows are tight—firmware usually rotates or splits probe 0, probe 1, and average across lines or timed pages." },
      { type: "h2", text: "Typical layout" },
      { type: "ul", items: ["**Row 0:** Probe 0 temp and humidity abbreviated (e.g. <code>P0 38F 41%</code>).","**Row 1:** Probe 1 or rolling average depending on sketch version.","**Backlight:** On during reads; optional timeout to reduce glare at night."] },
      { type: "h2", text: "Units and refresh" },
      { type: "p", html: "Match units to what you expect on the website or label the LCD. Refresh only when new valid reads arrive—avoid flicker from partial updates. GPIO wiring: <a class=\"text-link\" href=\"/about/liquid-crystal-gpio-map\">LCD GPIO map</a>." },
      { type: "h2", text: "When LCD disagrees with web" },
      { type: "p", html: "Compare against live JSON via curl—<a class=\"text-link\" href=\"/about/json-probe-output-schema\">JSON schema</a>. Stale cache on <a class=\"text-link\" href=\"/about/redis-cache-for-feeds\">Redis relay</a> can lag the LCD; local display is often fresher." }
  ],

  "dual-probe-averaging": [
      { type: "p", html: "The <code>avg</code> key summarizes healthy probes for quick glances and compact history rows. Averaging should ignore failed reads and optionally weight only probes marked active in firmware." },
      { type: "h2", text: "Algorithm sketch" },
      { type: "ol", items: ["Collect **valid** temperature and humidity pairs for each probe index.","Compute **arithmetic mean** separately for °F, °C, and humidity.","If only one probe is healthy, **avg may equal that probe** or be omitted—pick one policy."] },
      { type: "h2", text: "When not to trust avg" },
      { type: "p", html: "Door-adjacent and interior zones can differ by ten degrees—blind averaging hides freeze risk in the cold corner. Use avg for trend lines; use per-zone keys for decisions. Layout: <a class=\"text-link\" href=\"/about/multi-zone-garage-layout\">multi-zone layout</a>." },
      { type: "h2", text: "Related topics" },
      { type: "p", html: "Polling cadence: <a class=\"text-link\" href=\"/about/sketch-polling-main-loop\">sketch main loop</a>. Output shape: <a class=\"text-link\" href=\"/about/json-probe-output-schema\">JSON schema</a>." }
  ],

  "fastapi-relay-setup": [
      { type: "p", html: "A small FastAPI service on a home server or VPS can poll the Arduino over HTTP on the LAN, then expose a stable HTTPS URL to the internet. That keeps TLS and authentication off the microcontroller while preserving the JSON your dashboard already understands." },
      { type: "h2", text: "Minimal architecture" },
      { type: "ol", items: ["**Scheduler or on-demand fetch** hits <code>http://arduino.local/...</code> on the LAN.","**FastAPI route** returns the latest cached body with correct <code>Content-Type</code>.","**Reverse proxy** (Caddy, nginx) terminates TLS on a public hostname."] },
      { type: "h2", text: "Configuration tips" },
      { type: "ul", items: ["Set **reasonable timeouts**—garage uplink is slower than datacenter RTT.","Log **upstream errors** separately from client 404s.","Version the relay when <a class=\"text-link\" href=\"/about/json-probe-output-schema\">JSON schema</a> changes."] },
      { type: "h2", text: "Caching layer" },
      { type: "p", html: "Add <a class=\"text-link\" href=\"/about/redis-cache-for-feeds\">Redis cache</a> so Cloudflare Workers and the Astro site do not hammer your home IP on every page view. Security: <a class=\"text-link\" href=\"/about/relay-security-and-access\">relay security</a>." }
  ],

  "redis-cache-for-feeds": [
      { type: "p", html: "Redis stores the last good JSON payload with a TTL so burst traffic to your public HTTPS endpoint reads memory instead of opening a new LAN fetch every time. That protects both the Arduino and your residential router." },
      { type: "h2", text: "Cache policy" },
      { type: "ul", items: ["**TTL 30–120 seconds** matches how “live” the home page needs to feel.","**Stale-while-revalidate:** Serve old JSON while async refresh runs if upstream is slow.","**Key per feed URL** when multiple garages or benches exist."] },
      { type: "h2", text: "Failure modes" },
      { type: "p", html: "If Redis is empty and Arduino is down, return 503 with a clear log line—better than inventing zeros. Site-side handling: <a class=\"text-link\" href=\"/about/debugging-stale-readings\">debugging stale readings</a>. Relay setup: <a class=\"text-link\" href=\"/about/fastapi-relay-setup\">FastAPI relay setup</a>." },
      { type: "h2", text: "Data flow placement" },
      { type: "p", html: "See step 2 in <a class=\"text-link\" href=\"/about/data-flow\">end-to-end data flow</a>. History still lands in Supabase via <a class=\"text-link\" href=\"/about/supabase-history-inserts\">history inserts</a> on the website schedule." }
  ],

  "relay-security-and-access": [
      { type: "p", html: "Publishing garage telemetry to the internet invites scanning. Lock down who can read feeds, rate-limit public endpoints, and never expose the Arduino JSON port directly without understanding the risk." },
      { type: "h2", text: "Hardening checklist" },
      { type: "ul", items: ["**HTTPS only** on public URLs; HSTS at the reverse proxy.","**Optional API keys** or signed tokens for non-browser clients.","**Firewall** the Arduino to LAN-only; only the relay reaches it.","**No secrets** in firmware source committed to public repos."] },
      { type: "h2", text: "Dashboard integration" },
      { type: "p", html: "Users paste HTTPS feed URLs in <a class=\"text-link\" href=\"/about/configuring-temperature-feeds\">temperature feed settings</a>. The site stores URLs per account—pair with <a class=\"text-link\" href=\"/about/supabase-auth-flow\">Supabase auth</a> so feeds are not world-editable." },
      { type: "h2", text: "Compare stacks" },
      { type: "p", html: "Node and Next patterns for APIs: <a class=\"text-link\" href=\"/about/node-express-api-patterns\">Node Express API patterns</a>. This project uses Astro fetch routes—<a class=\"text-link\" href=\"/about/astro-server-side-rendering\">Astro SSR</a>." }
  ],

  "astro-server-side-rendering": [
      { type: "p", html: "Astro renders most pages on the server at request time or build time, shipping HTML with minimal client JavaScript. For a monitoring site, that means fast first paint for public probe cards and SEO-friendly about documentation without a heavy SPA bundle." },
      { type: "h2", text: "SSR in this project" },
      { type: "p", html: "The home page fetches live JSON during SSR via <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">server-side probe fetch</a>. About articles are static content with optional expanded blocks from generated TypeScript. API routes handle auth and history writes." },
      { type: "h2", text: "Benefits for monitoring" },
      { type: "ul", items: ["**Secrets stay server-side**—feed URLs and Supabase keys never ship to the browser wholesale.","**Edge deployment** on Cloudflare reduces latency—see <a class=\"text-link\" href=\"/about/cloudflare-workers-deployment\">Cloudflare Workers deployment</a>.","**Progressive enhancement** for dashboard features that need client state."] },
      { type: "h2", text: "Related reading" },
      { type: "p", html: "Interactive widgets use <a class=\"text-link\" href=\"/about/astro-islands-and-hydration\">Astro islands</a>. Compare with <a class=\"text-link\" href=\"/about/nextjs-monitoring-dashboards\">Next.js monitoring dashboards</a>." }
  ],

  "astro-islands-and-hydration": [
      { type: "p", html: "Islands are interactive UI fragments hydrated with client-side JavaScript while the surrounding page stays static. Charts, auth forms, and feed editors hydrate; long-form about text does not." },
      { type: "h2", text: "Where hydration helps" },
      { type: "ul", items: ["**History charts** needing client-side zoom or tooltips.","**Dashboard forms** for <a class=\"text-link\" href=\"/about/configuring-temperature-feeds\">configuring feeds</a>.","**Probe demo** toggles on the <a class=\"text-link\" href=\"/about/probe-demo\">interactive demo</a> page."] },
      { type: "h2", text: "Performance habit" },
      { type: "p", html: "Default to zero JS; add <code>client:load</code> or <code>client:visible</code> only where necessary. Public visitors mostly read static SSR output from <a class=\"text-link\" href=\"/about/astro-server-side-rendering\">Astro SSR</a>." },
      { type: "h2", text: "Stack context" },
      { type: "p", html: "Full pipeline: <a class=\"text-link\" href=\"/about/data-flow\">data flow</a>. Admin tools: <a class=\"text-link\" href=\"/about/admin-dashboard-features\">admin dashboard features</a>." }
  ],

  "cloudflare-workers-deployment": [
      { type: "p", html: "This site targets Cloudflare Workers/Pages via the Astro adapter so HTML and API routes run at the edge close to visitors. Probe fetch latency improves versus a single-region VPS for a globally readable demo." },
      { type: "h2", text: "Deployment considerations" },
      { type: "ol", items: ["**Environment variables** for Supabase and Stripe live in Cloudflare dashboard secrets.","**Fetch timeouts** to residential feed URLs must tolerate slow home uplinks.","**Cron or scheduled triggers** may drive <a class=\"text-link\" href=\"/about/supabase-history-inserts\">history inserts</a>."] },
      { type: "h2", text: "Caching interaction" },
      { type: "p", html: "Do not cache authenticated dashboard HTML at the CDN edge. Public home page caching should respect how fresh probes need to be—often aligned with <a class=\"text-link\" href=\"/about/redis-cache-for-feeds\">Redis TTL</a> upstream." },
      { type: "h2", text: "Alternatives" },
      { type: "p", html: "<a class=\"text-link\" href=\"/about/comparing-full-stack-options\">Comparing full-stack options</a> covers Node hosting versus edge Astro." }
  ],

  "nextjs-monitoring-dashboards": [
      { type: "p", html: "Next.js excels at authenticated dashboards with React Server Components, API routes, and a vast component ecosystem. A garage monitor could be built entirely in Next—fetching probes in server components and charting in client charts." },
      { type: "h2", text: "Typical Next layout" },
      { type: "ul", items: ["**app/dashboard/page.tsx** server-fetches JSON feeds with cached revalidation.","**Route handlers** proxy probes to hide LAN URLs—similar to <a class=\"text-link\" href=\"/about/fastapi-relay-setup\">FastAPI relay</a>.","**Middleware** guards signed-in pages using <a class=\"text-link\" href=\"/about/supabase-auth-flow\">Supabase auth</a> patterns."] },
      { type: "h2", text: "Why this project uses Astro" },
      { type: "p", html: "Documentation-heavy about pages and minimal JS for public visitors fit Astro’s content-first model. Edge deployment on Cloudflare is first-class—<a class=\"text-link\" href=\"/about/cloudflare-workers-deployment\">Workers deployment</a>." },
      { type: "h2", text: "Further comparison" },
      { type: "p", html: "See <a class=\"text-link\" href=\"/about/comparing-full-stack-options\">comparing full-stack options</a> and <a class=\"text-link\" href=\"/about/node-express-api-patterns\">Express API patterns</a>." }
  ],

  "node-express-api-patterns": [
      { type: "p", html: "Express (or Fastify) on Node remains a straightforward choice for JSON APIs, webhooks, and cron jobs. A monitoring stack might use Express to poll probes, write Supabase rows, and serve CSV export links." },
      { type: "h2", text: "Common routes" },
      { type: "ol", items: ["<code>GET /api/feeds/:id</code> — cached probe JSON for dashboards.","<code>POST /webhooks/stripe</code> — unlock <a class=\"text-link\" href=\"/about/stripe-csv-subscription\">CSV subscription</a> features.","<code>GET /export/history.csv</code> — authenticated download."] },
      { type: "h2", text: "Operational notes" },
      { type: "ul", items: ["Run behind **HTTPS reverse proxy** with rate limits.","Use **connection pooling** for Supabase Postgres if querying directly.","Prefer **idempotent webhooks** for Stripe events."] },
      { type: "h2", text: "Parallel in Astro" },
      { type: "p", html: "This repo implements similar endpoints as Astro server routes—<a class=\"text-link\" href=\"/about/supabase-history-inserts\">history inserts</a> and <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">probe fetch</a>." }
  ],

  "comparing-full-stack-options": [
      { type: "p", html: "Garage monitoring needs three things: periodic probe ingestion, authenticated storage, and a readable public face. Astro, Next.js, and plain Node each cover the triangle with different tradeoffs in JS payload, hosting, and developer ergonomics." },
      { type: "h2", text: "Decision matrix" },
      { type: "ul", items: ["**Astro + edge:** Best here for content, light public JS, Cloudflare deploy—<a class=\"text-link\" href=\"/about/astro-applications\">Astro applications</a>.","**Next.js:** Rich client dashboards, Vercel-native workflows—<a class=\"text-link\" href=\"/about/nextjs-monitoring-dashboards\">Next dashboards</a>.","**Node + Express:** Maximum control, long-running cron on a VPS—<a class=\"text-link\" href=\"/about/node-express-api-patterns\">Express patterns</a>.","**Python relay:** TLS and cache at home—<a class=\"text-link\" href=\"/about/python-feeds\">Python feeds</a>."] },
      { type: "h2", text: "Shared backend" },
      { type: "p", html: "Supabase auth and Postgres history are stack-agnostic—<a class=\"text-link\" href=\"/about/accounts-and-dashboard\">accounts and dashboard</a>. Data pipeline: <a class=\"text-link\" href=\"/about/data-flow\">data flow</a>." }
  ],

  "home-page-probe-fetch": [
      { type: "p", html: "The public home page shows live probe cards by server-fetching configured HTTPS JSON feeds during Astro SSR. The browser receives HTML with numbers already resolved—no client-side CORS dance to residential IPs." },
      { type: "h2", text: "Fetch sequence" },
      { type: "ol", items: ["Load **enabled feed URLs** and probe mappings for the site owner or demo account.","Server **HTTP GET** each feed with timeout and error handling.","Parse **temp object** per <a class=\"text-link\" href=\"/about/json-probe-output-schema\">JSON schema</a> and apply labels.","Render **stat cards** in HTML returned to the visitor."] },
      { type: "h2", text: "Failure display" },
      { type: "p", html: "Missing keys or timeout should degrade gracefully—show last error state or omit a card rather than 500 the whole page. Diagnosis: <a class=\"text-link\" href=\"/about/debugging-stale-readings\">debugging stale readings</a>." },
      { type: "h2", text: "Configuration source" },
      { type: "p", html: "Mappings come from <a class=\"text-link\" href=\"/about/configuring-temperature-feeds\">dashboard feed settings</a>. Upstream cache: <a class=\"text-link\" href=\"/about/redis-cache-for-feeds\">Redis cache</a>. Broader pipeline: <a class=\"text-link\" href=\"/about/data-flow\">data flow overview</a>." }
  ],

  "supabase-history-inserts": [
      { type: "p", html: "Historical charts depend on periodic inserts into Supabase Postgres—not on the browser remembering prior values. A scheduled job or edge function polls feeds and writes normalized rows keyed by user and probe." },
      { type: "h2", text: "Insert model" },
      { type: "ul", items: ["**Timestamp + user_id + probe_key** uniquely identify a sample.","Store **temp, humidity, units** as typed columns for fast chart queries.","Skip insert if **upstream fetch failed** to avoid flatlines at zero."] },
      { type: "h2", text: "Auth boundary" },
      { type: "p", html: "Row-level security ties history to signed-in users—<a class=\"text-link\" href=\"/about/supabase-auth-flow\">Supabase auth flow</a>. Only the service role or trusted server route should insert on schedule." },
      { type: "h2", text: "Consumption" },
      { type: "p", html: "Dashboard reads via <a class=\"text-link\" href=\"/about/history-dashboard-browsing\">history browsing</a>; export via <a class=\"text-link\" href=\"/about/csv-export-spreadsheet-analysis\">CSV export</a>. Live path: <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">home page fetch</a>." }
  ],

  "debugging-stale-readings": [
      { type: "p", html: "Stale readings mean the website shows an old temperature while the garage has moved on—or shows nothing while the LCD still updates. Work from the sensor outward: hardware, JSON, cache, SSR fetch, then history." },
      { type: "h2", text: "Checklist" },
      { type: "ol", items: ["**curl the feed URL** from outside your LAN—is JSON fresh?","Compare **LCD vs JSON**—if LCD wins, fix relay or <a class=\"text-link\" href=\"/about/redis-cache-for-feeds\">Redis TTL</a>.","Verify **probe keys** in dashboard match schema—<a class=\"text-link\" href=\"/about/probe-mapping-labels\">probe mapping</a>.","Inspect **Cloudflare / SSR logs** for timeout patterns."] },
      { type: "h2", text: "Hardware-side causes" },
      { type: "p", html: "<a class=\"text-link\" href=\"/about/firmware-watchdog-recovery\">Watchdog reboots</a> cause short gaps. <a class=\"text-link\" href=\"/about/dht22-read-errors-retries\">DHT22 errors</a> drop keys from JSON. Ethernet: <a class=\"text-link\" href=\"/about/circuit-wiring-troubleshooting\">wiring troubleshooting</a>." },
      { type: "h2", text: "History vs live" },
      { type: "p", html: "Charts can lag if inserts stop but home page still looks live—check <a class=\"text-link\" href=\"/about/supabase-history-inserts\">history inserts</a> separately from <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">home page fetch</a>." }
  ],

  "supabase-auth-flow": [
      { type: "p", html: "User accounts use Supabase Auth for email or OAuth sign-in, session cookies, and row-level security on history and feed configuration. The Astro site validates sessions on protected routes before rendering dashboard HTML or API mutations." },
      { type: "h2", text: "Session lifecycle" },
      { type: "ol", items: ["User signs in via **Supabase client** or server exchange.","Session **cookie** scoped to site domain; HttpOnly where configured.","Server routes read session and **query Postgres** with user context."] },
      { type: "h2", text: "What auth protects" },
      { type: "ul", items: ["**Feed URLs and probe labels**—<a class=\"text-link\" href=\"/about/configuring-temperature-feeds\">temperature feeds</a>.","**History rows**—<a class=\"text-link\" href=\"/about/history-dashboard-browsing\">history browsing</a>.","**CSV export**—<a class=\"text-link\" href=\"/about/stripe-csv-subscription\">subscription gating</a>.","**Admin tools**—<a class=\"text-link\" href=\"/about/admin-dashboard-features\">admin features</a>."] },
      { type: "h2", text: "Security notes" },
      { type: "p", html: "Never expose service role keys to the browser. Relay security for public JSON: <a class=\"text-link\" href=\"/about/relay-security-and-access\">relay security</a>." }
  ],

  "stripe-csv-subscription": [
      { type: "p", html: "CSV export of temperature history is a subscription feature billed through Stripe. Checkout creates a customer portal link; webhooks flip a flag in Supabase so export buttons unlock without manual admin work." },
      { type: "h2", text: "User flow" },
      { type: "ol", items: ["Signed-in user opens **billing** from the dashboard.","Stripe **Checkout** completes payment method capture.","Webhook marks **subscription active**; user downloads CSV from history."] },
      { type: "h2", text: "Export contents" },
      { type: "p", html: "Files mirror stored history columns—see <a class=\"text-link\" href=\"/about/csv-export-spreadsheet-analysis\">CSV analysis guide</a>. Live data path remains separate: <a class=\"text-link\" href=\"/about/data-flow\">data flow</a>." },
      { type: "h2", text: "Implementation peers" },
      { type: "p", html: "Webhook handling patterns overlap with <a class=\"text-link\" href=\"/about/node-express-api-patterns\">Express webhooks</a>. Auth prerequisite: <a class=\"text-link\" href=\"/about/supabase-auth-flow\">Supabase auth</a>." }
  ],

  "configuring-temperature-feeds": [
      { type: "p", html: "After sign-in, users paste HTTPS URLs pointing at probe JSON—often a FastAPI relay with Redis—and map each numeric key to a human-readable label. Those settings drive both the public home page and history sampling." },
      { type: "h2", text: "Setup steps" },
      { type: "ol", items: ["Verify feed with **curl** against <a class=\"text-link\" href=\"/about/json-probe-output-schema\">expected schema</a>.","Add URL in **dashboard feed settings**; enable desired probe keys.","Assign **labels** per <a class=\"text-link\" href=\"/about/probe-mapping-labels\">probe mapping guide</a>.","Wait one **poll cycle** and confirm home page cards update."] },
      { type: "h2", text: "Multiple feeds" },
      { type: "p", html: "Advanced setups may separate demo and production relays—document which URL is public. Security: <a class=\"text-link\" href=\"/about/relay-security-and-access\">relay security</a>. Fetch implementation: <a class=\"text-link\" href=\"/about/home-page-probe-fetch\">home page probe fetch</a>." },
      { type: "h2", text: "Troubleshooting" },
      { type: "p", html: "<a class=\"text-link\" href=\"/about/debugging-stale-readings\">Debugging stale readings</a> when labels look right but numbers do not move." }
  ],

  "admin-dashboard-features": [
      { type: "p", html: "Admin-only dashboard areas support operators who manage demo content, review user issues, or inspect system health. Role checks run server-side alongside standard <a class=\"text-link\" href=\"/about/supabase-auth-flow\">Supabase auth</a>—never gate solely with hidden client buttons." },
      { type: "h2", text: "Typical admin capabilities" },
      { type: "ul", items: ["**User lookup** for feed misconfiguration support tickets.","**Feature flags** for beta chart types or export limits.","**Audit logs** of webhook and insert failures tied to <a class=\"text-link\" href=\"/about/supabase-history-inserts\">history inserts</a>."] },
      { type: "h2", text: "Deployment" },
      { type: "p", html: "Admin routes deploy with the same <a class=\"text-link\" href=\"/about/cloudflare-workers-deployment\">Cloudflare Workers</a> bundle as public pages—protect with role claims in JWT or a separate allowlist table." },
      { type: "h2", text: "Related product docs" },
      { type: "p", html: "End users see <a class=\"text-link\" href=\"/about/accounts-and-dashboard\">accounts and dashboard overview</a>, <a class=\"text-link\" href=\"/about/history-dashboard-browsing\">history</a>, and <a class=\"text-link\" href=\"/about/stripe-csv-subscription\">Stripe subscription</a> flows." }
  ]
};

export const EXPANDED_ABOUT_SLUGS: readonly string[] = [
  "dht22-sensor-overview",
  "probe-mounting-enclosures",
  "multi-zone-garage-layout",
  "probe-mapping-labels",
  "garage-door-temperature-swings",
  "sun-load-garage-walls",
  "infiltration-wind-drafts",
  "seasonal-garage-patterns",
  "history-dashboard-browsing",
  "csv-export-spreadsheet-analysis",
  "freeze-protection-thresholds",
  "arduino-ide-setup",
  "sketch-polling-main-loop",
  "json-probe-output-schema",
  "firmware-watchdog-recovery",
  "breadboard-power-rails",
  "ethernet-shield-stacking",
  "circuit-wiring-troubleshooting",
  "liquid-crystal-gpio-map",
  "dht22-data-line-wiring",
  "spi-pins-ethernet-reserved",
  "dht22-read-errors-retries",
  "lcd-local-display-format",
  "dual-probe-averaging",
  "fastapi-relay-setup",
  "redis-cache-for-feeds",
  "relay-security-and-access",
  "astro-server-side-rendering",
  "astro-islands-and-hydration",
  "cloudflare-workers-deployment",
  "nextjs-monitoring-dashboards",
  "node-express-api-patterns",
  "comparing-full-stack-options",
  "home-page-probe-fetch",
  "supabase-history-inserts",
  "debugging-stale-readings",
  "supabase-auth-flow",
  "stripe-csv-subscription",
  "configuring-temperature-feeds",
  "admin-dashboard-features"
] as const;

export const expandedAboutSlugs: Set<string> = new Set(EXPANDED_ABOUT_SLUGS);

export function getExpandedAboutContent(
  slug: string,
): AboutContentBlock[] | undefined {
  return expandedAboutContent[slug];
}
